services:
  agencia_autos_db:
    image: postgres:15
    container_name: agencia_autos_db
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=agencia_autos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agencia_network

  agencia_autos_api:
    build: .
    container_name: agencia_autos_api
    ports:
      - "8000:8000"
    depends_on:
      - agencia_autos_db
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@agencia_autos_db:5432/agencia_autos_db
    volumes:
      - .:/app
    networks:
      - agencia_network

networks:
  agencia_network:
    driver: bridge

volumes:
  postgres_data: